services:
  daemon:
    image: ghcr.io/perlenjaeger/paperless-to-lexoffice:latest
    build:
      context: ../
      # for lexware api
      # dockerfile: Dockerfile
      # big playwright image necessary without api access
      dockerfile: Dockerfile.playwright
    container_name: paperless-to-lexoffice
    env_file:
      - .env
    restart: unless-stopped
